# Generated by Django 3.2 on 2022-02-22 08:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
