# Generated by Django 3.2 on 2022-02-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.JSONField(null=True),
        ),
    ]
