# Generated by Django 3.2 on 2022-02-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='patient/'),
        ),
    ]
